[package]
name = "hyraid_json"
edition.workspace = true
authors.workspace = true
version.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
hyraid_types.workspace = true

serde_json.workspace = true