[package]
name = "hyraid_json"
edition.workspace = true
authors.workspace = true
version.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
serde_json = "1.0.141"
hyraid_types = { workspace = true }