[package]
name = "hyraid_mdadm"
edition.workspace = true
authors.workspace = true
version.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
hyraid_utils.workspace = true

regex.workspace = true
