[package]
name = "hyraid_types"
edition.workspace = true
authors.workspace = true
version.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
gpt.workspace = true

hyraid_gpt.workspace = true
